### ISSUE TITLE
Visualization mode: Data flows for selected state only

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#377] opened 2020-04-17 09:58 UTC
A visualization mode, where only the data flows of the currently selected state is shown, would highly improve the overview for complex state machines.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-07-19 08:14:29+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment] 2024-12-13 12:02
Duplicate of https://github.com/DLR-RM/RAFCON/discussions/937

**Closed by JohannesErnst** 2024-12-13 12:02 UTC
Labels: enhancement
